version: 2.1

jobs:
  integration-test:
    docker:
      - image: josephlwalker96/freewilli-exec:latest
        network: host # Ensures UDP packets are sent/received
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Run Integration Test
          command: |
            chmod +x integration_testing/test_integration.sh
            ./integration_testing/test_integration.sh

workflows:
  version: 2
  test:
    jobs:
      - integration-test