version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03  # Base image for build job
    steps:
      - checkout
      - run:
          name: Build step
          command: echo "This is the build step"

  integration-test:
    docker:
      - image: docker:20.10  # Use Docker-in-Docker
    steps:
      - setup_remote_docker:
          version: 20.10  # Enable Docker inside CircleCI
      - checkout
      - run:
          name: Pull Docker Image
          command: docker pull josephlwalker96/freewilli-exec:latest
      - run:
          name: Run Integration Test
          command: |
            docker run --rm -v $(pwd):/app -w /app josephlwalker96/freewilli-exec ./integration_testing/test_integration.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - integration-test:
          requires:
            - build

