version: 2.1

jobs:
  integration-test:
    docker:
      - image: docker:20.10  # Use Docker-in-Docker
    steps:
      - setup_remote_docker:
          version: 20.10  # Enable Docker inside CircleCI
      - checkout
      - run:
          name: Load Docker Image
          command: docker pull josephlwalker96/freewilli-exec:latest
      - run:
          name: Run Integration Test
          command: |
            docker run --rm --network host -v $(pwd):/app josephlwalker96/freewilli-exec ./integration_testing/test_integration.sh
