version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Build step
          command: echo "This is the build step"

  integration-test:
    docker:
      - image: docker:20.10
    steps:
      - setup_remote_docker:
          version: 20.10
      - checkout:
          path: /home/circleci/project  # Explicitly set checkout path
      - run:
          name: Debug - Show Checkout Path
          command: pwd && ls -l
      - run:
          name: Debug - List All Files
          command: find . -type f
      - run:
          name: Pull Docker Image
          command: docker pull josephlwalker96/freewilli-exec:latest
      - run:
          name: Run Integration Test
          command: |
            docker run --rm -v /home/circleci/project:/app josephlwalker96/freewilli-exec bash -c "ls -l /app && ls -l /app/integration_testing && ./integration_testing/test_integration.sh"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - integration-test:
          requires:
            - build


